apiVersion: v1
kind: Service
metadata:
  name: bank-mysql
  namespace: default
  labels:
    app: bank-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: bank-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-mysql
  labels:
    app: bank-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-mysql
  template:
    metadata:
      labels:
        app: bank-mysql
    spec:
      containers:
        - name: bank-mysql
          image: mysql:8.0.33
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"